DELETE FROM USERS where ID_USER > 0;
DELETE FROM FILMS where ID_FILMS > 0;
DELETE FROM LIKES where FILM_ID > 0;
DELETE FROM FRIENDS where USER_ID > 0;
DELETE FROM FILM_GENRES where FILM_ID > 0;
ALTER TABLE USERS ALTER COLUMN ID_USER RESTART WITH 1;
ALTER TABLE FILMS ALTER COLUMN ID_FILMS RESTART WITH 1;


MERGE INTO GENRES (ID_GENRES, NAME_GENRES) values (1, 'Комедия');
MERGE INTO GENRES (ID_GENRES, NAME_GENRES) values (2, 'Драма');
MERGE INTO GENRES (ID_GENRES, NAME_GENRES) values (3, 'Мультфильм');
MERGE INTO GENRES (ID_GENRES, NAME_GENRES) values (4, 'Триллер');
MERGE INTO GENRES (ID_GENRES, NAME_GENRES) values (5, 'Документальный');
MERGE INTO GENRES (ID_GENRES, NAME_GENRES) values (6, 'Боевик');

MERGE INTO MPA (ID_MPA, NAME_MPA) VALUES (1, 'G');
MERGE INTO MPA (ID_MPA, NAME_MPA) VALUES (2, 'PG');
MERGE INTO MPA (ID_MPA, NAME_MPA) VALUES (3, 'PG-13');
MERGE INTO MPA (ID_MPA, NAME_MPA) VALUES (4, 'R');
MERGE INTO MPA (ID_MPA, NAME_MPA) VALUES (5, 'NC-17');






