

CREATE TABLE IF NOT EXISTS GENRES (
    id_genres INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genres varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA (
    id_mpa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_mpa varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS (
    id_films INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_films varchar(100) NOT NULL,
    description varchar(200) NOT NULL,
    release_date datetime,
    duration int NOT NULL,
    mpa INTEGER REFERENCES MPA (id_mpa)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
    film_id INTEGER REFERENCES FILMS (id_films) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES GENRES (id_genres),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS USERS (
    id_user  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar(100) NOT NULL,
    name_user varchar(100),
    birthday datetime
);

CREATE TABLE IF NOT EXISTS LIKES (
  film_id INTEGER REFERENCES FILMS (id_films),
  user_id INTEGER REFERENCES USERS (id_user),
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS FRIENDS (
  user_id INTEGER REFERENCES USERS (id_user),
  other_id INTEGER REFERENCES USERS (id_user),
  PRIMARY KEY (user_id, other_id)
);

